steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/logging-node-app", "."]

  # Step 2: Push the Docker image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/logging-node-app"]

  # Step 3: Deploy the image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "logging-node-app"
      - "--image"
      - "gcr.io/$PROJECT_ID/logging-node-app"
      - "--platform"
      - "managed"
      - "--region"
      - "us-central1"
      - "--allow-unauthenticated"
      - "--add-cloudsql-instances"
      - "$PROJECT_ID:us-central1:your-cloudsql-instance"
      - "--update-env-vars"
      - "DB_USER=your_db_user,DB_PASSWORD=your_db_password,DB_NAME=your_db_name,DB_HOST=/cloudsql/$PROJECT_ID:us-central1:your-cloudsql-instance"

# Specify the Cloud Build trigger
images:
  - "gcr.io/$PROJECT_ID/logging-node-app"
